name: CI/CD Pipeline
 
on:
  push:
    branches:
      - main
      - develop
  pull_request:
 
jobs:
  test-backend:
    runs-on: ubuntu-22.04
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0
 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
 
      # Étape : Analyse avec SonarCloud
      - name: Analyze code with SonarCloud
        run: |
          cd simple-api
          mvn -B verify sonar:sonar \
              -Dsonar.projectKey=thuy29_devops-livecoding \
              -Dsonar.organization=thuy29 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
 
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
 
    steps:
      # Étape 1 : Checkout du code source
      - name: Checkout repository
        uses: actions/checkout@v2.5.0
 
      # Étape 2 : Login à Docker Hub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
 
      # Étape 3 : Construire et pousser l'image backend
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}
 
      # Étape 4 : Construire et pousser l'image database
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}
 
      # Étape 5 : Construire et pousser l'image HTTPD
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}