name: CI DevOps

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Set up Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

    
      - name: Analyze code with SonarCloud
        run: |
          cd simple-api
          mvn -B verify sonar:sonar \
              -Dsonar.projectKey=thuy29_devops-livecoding \
              -Dsonar.organization=thuy29 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.ci.mode=true

 
 
  build-and-push-docker-image:
    needs: test-backend
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and push backend
        run: |
          docker build ./simple-api --file ./simple-api/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/tp-devops-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/tp-devops-api:latest

      - name: Build image and push database
        run: |
          docker build ./database --file ./database/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/tp-devops-db:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/tp-devops-db:latest
  
      - name: Build image and push httpd
        run: |
          docker build ./http-server --file ./http-server/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/tp-devops-http:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/tp-devops-http:latest
